name: PR Label-based Discord Notification

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord based on PR label
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"

          LABELS=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')

          for LABEL in $LABELS; do
            case "$LABEL" in
              "BE")
                WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_BACKEND }}"
                MESSAGE="PR #$PR_NUMBER: $PR_TITLE\n$PR_URL"
                ;;
              "FE")
                WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_FRONTEND }}"
                MESSAGE="PR #$PR_NUMBER: $PR_TITLE\n$PR_URL"
                ;;
              *)
                continue
                ;;
            esac

            curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"$MESSAGE\"}" \
              "$WEBHOOK_URL"
          done
