name: PR Label-based Discord Notification

on:
  pull_request:
    types: [opened, labeled, synchronize]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_LABELS_JSON: ${{ toJson(github.event.pull_request.labels) }}

    steps:
      - name: Print PR Labels JSON
        run: |
          echo "=== Raw PR_LABELS_JSON ==="
          
          LABELS=$(echo "$PR_LABELS_JSON" | jq -r '.[].name')
          echo $LABELS
    
      - name: Notify Discord based on PR label
        run: |
          LABELS=$(echo "$PR_LABELS_JSON" | jq -r '.[].name')

          for LABEL in $LABELS; do
            case "$LABEL" in
              "BE")
                WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_BACKEND }}"
                MESSAGE="$PR_URL"
                ;;
              "FE")
                WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_FRONTEND }}"
                MESSAGE="$PR_URL"
                ;;
              *)
                continue
                ;;
            esac

            PAYLOAD=$(jq -n --arg content "$MESSAGE" '{content: $content}')
            echo "====WEBHOOK_URL===="
            echo "$WEBHOOK_URL"
            
            curl --fail -H "Content-Type: application/json" \
              -X POST \
              -d "$PAYLOAD" \
              "$WEBHOOK_URL"
          done
