name: Setup Closed Issues

on:
  issues:
    types: [ closed ]

jobs:
  setup_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Set End date
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_V2_TOKEN }}
          script: |
            const projectId = 'PVT_kwHOAaxoFs4A9lXt';
            const issueId = context.payload.issue.node_id;

            // 1) 이슈를 프로젝트에 추가 (이미 있으면 기존 item id를 반환)
            const addResp = await github.graphql(
              `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: { projectId: $projectId, contentId: $contentId }) {
                  item { id }
                }
              }
              `,
              { projectId, contentId: issueId }
            );
            const itemId = addResp.addProjectV2ItemById.item.id;

            // 2) End date 필드 id 조회
            const fieldData = await github.graphql(`
              query($projectId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    fields(first: 100) {
                      nodes {
                        __typename
                        ... on ProjectV2FieldCommon { id name }
                      }
                    }
                  }
                }
              }
            `, { projectId });

            const fields = fieldData.node.fields.nodes;
            const endDateField = fields.find(f => f.name?.toLowerCase() === 'end date');
            if (!endDateField) {
              console.log('End date 필드를 찾지 못했습니다.');
              return;
            }

            // 3) 종료일 = 이슈 closedAt(웹훅의 close 시각) 또는 오늘 날짜
            const closedAt = context.payload.issue.closed_at; // ISO 8601
            const dateStr = (closedAt ? new Date(closedAt) : new Date())
              .toISOString().split('T')[0];

            // 4) 필드값 업데이트
            await github.graphql(
              `
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $date: Date!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: { date: $date }
                }) {
                  projectV2Item { id }
                }
              }
              `,
              { projectId, itemId, fieldId: endDateField.id, date: dateStr }
            );
