name: Setup Closed Issues

on:
  issues:
    types: [ closed ]

jobs:
  setup_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Set End date
        continue-on-error: true
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_V2_TOKEN }}
          script: |
            const { issue } = context.payload;

            const itemId = issue.node_id;

            // Project v2 ID
            const projectNodeId = 'PVT_kwHOAaxoFs4A9lXt';

            // Project의 필드 목록 조회
            const fieldData = await github.graphql(`
              query {
                node(id: "${projectNodeId}") {
                  ... on ProjectV2 {
                    fields(first: 50) {
                      nodes {
                        __typename
                        ... on ProjectV2FieldCommon {
                            id
                            name
                        }
                      }
                    }
                  }
                }
              }
            `);
            const fields = fieldData.node.fields.nodes;
            
            // End date 필드를 issue를 close한 날짜 설정
            const endDateField = fields.find(f =>
              f.__typename === 'ProjectV2Field' &&
              f.name?.toLowerCase() === 'end date'
            );
            const endDateFieldId = endDateField?.id;
            
            const closedAt = issue.closed_at;
            const closedAtISOString = closedAt.toISOString().split('T')[0];
            
            if (endDateFieldId) {
              await github.graphql(`
                mutation {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: "${projectNodeId}",
                    itemId: "${itemId}",
                    fieldId: "${endDateFieldId}",
                    value: { date: "${closedAtISOString}" }
                  }) {
                    projectV2Item { id }
                  }
                }
              `);
            }
